name: Vouchers Build

on:
  push:
    paths:
      - 'src/**'
      - 'pom.xml'
      - '.github/workflows/maven.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-package: jdk
          java-version: 1.8

      - name: Build with Maven
        run: mvn verify -B --file pom.xml
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: target/Vouchers-*.jar
          retention-days: 7

  jitpack:
    runs-on: ubuntu-latest
    steps:
      - uses: badasintended/autojitpack@v0
